[app]
address = ":8000"

[db]
#driver = "mysql"
#connect = "root:@tcp(localhost:3306)/nlan?charset=utf8"
driver = "sqlite3"
connect = "../nlan/data/nlan.db"

[auth]
username = "admin"
password = "123"
secret = "123"
